from datetime import datetime
from typing import Dict, Any, List
import json

class ReportGenerator:
    """Generate formatted reports"""
    
    def get_timestamp(self) -> str:
        """Get current timestamp"""
        return datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    def format_summary_report(self, data: Dict[str, Any]) -> str:
        """Format summary as readable text"""
        report = f"""
╔══════════════════════════════════════════════════════════╗
║           HR ANALYTICS SUMMARY REPORT                    ║
╠══════════════════════════════════════════════════════════╣
║ Generated: {self.get_timestamp():^40} ║
╚══════════════════════════════════════════════════════════╝

OVERVIEW:
---------
Total Candidates: {data.get('total_candidates', 0)}
Avg Resume Score: {data.get('avg_resume_score', 0)}
Avg Interview Score: {data.get('avg_interview_score', 0)}

INSIGHTS:
---------
{data.get('ai_insights', 'No insights available')}

"""
        return report
    
    def export_json(self, data: Dict[str, Any], filename: str):
        """Export data as JSON"""
        try:
            with open(filename, 'w') as f:
                json.dump(data, f, indent=2)
            return True
        except Exception as e:
            return False
    
    def generate_markdown_report(self, data: Dict[str, Any]) -> str:
        """Generate markdown format report"""
        md = f"""# HR Analytics Report

**Generated:** {self.get_timestamp()}

## Summary

- **Total Candidates:** {data.get('total_candidates', 0)}
- **Average Resume Score:** {data.get('avg_resume_score', 0)}
- **Average Interview Score:** {data.get('avg_interview_score', 0)}

## Insights

{data.get('ai_insights', 'No insights available')}

---
*Generated by HR Multi-Agent Intelligence Suite*
"""
        return md